Feature/display
elcojacobs/brewblox-firmware pull request #1
Opened 2021-06-04 12:53 UTC by CvRXX

2021-06-04 12:56 UTC, elcojacobs commented on app/brewblox-esp/main/graphics.hpp
> +            ESP_LOGE("Flush", "Writing zero pixels");
remove logs

2021-06-04 12:56 UTC, CvRXX commented on app/brewblox-esp/main/graphics.hpp
> +            ESP_LOGE("Flush", "Writing zero pixels");
Dit mag eruit.

2021-06-04 13:01 UTC, elcojacobs commented on app/brewblox-esp/main/graphics.hpp
> +        getInstance().display.writePixels(area->x1, area->x2, area->y1, area->y2, reinterpret_cast<uint8_t*>(color_p), nPixels);
should this singleton be a class? Should getInstance() exist?
Data could also move into cpp in namespace

2021-06-04 14:50 UTC, elcojacobs requested changes

2021-06-04 14:50 UTC, elcojacobs commented on lib/test/ringBuffer_test.cpp
> +TEST_CASE("Elements can be taken from the ringbuffer", "[ringBuffer]")
if multiple spi clients can put transfers in the ring buffer, they should only be able to do so if the bus is aquired or free. Otherwise the order of input and output is mismatched

2021-06-04 14:50 UTC, elcojacobs commented on platform/esp/TFT035.cpp
> +TFT035::TFT035(std::function<void()> finishCallback)
store callbacks in transactions as references to avoid copying objects that are actually static.

2021-06-04 14:50 UTC, elcojacobs commented on platform/esp/TFT035.cpp
> +    return spiDevice.write(pixels, nPixels * 3, true, callbackDcPinOn, [&](TransactionData& t) {
unnecessary construction of lambda to static function if callbacks in transaction are refs

2021-06-04 14:50 UTC, elcojacobs commented on platform/esp/TFT035.cpp
> +TFT035::TFT035(std::function<void()> finishCallback)
virtual base
super with member std::functions
super with member const std::function &

2021-06-04 14:50 UTC, elcojacobs commented on platform/esp/TFT035.hpp
>  #include "esp32/rom/ets_sys.h"
esp32 include still needed?

2021-06-04 14:50 UTC, elcojacobs commented on platform/esp/hal_spi_esp.cpp
> +auto transactionBuffer = RingBuffer<spi_transaction_t, 10>();
why not a single buffer with a struct containing both?

2021-06-04 14:50 UTC, elcojacobs commented on platform/esp/hal_spi_esp.cpp
> +        .tx_len = t->length,
platform type has length in bits, hal type in bytes?

2021-06-04 14:50 UTC, elcojacobs commented on platform/esp/hal_spi_esp.cpp
> +    t->length = transactionData.tx_len;
note length in bits here too

2021-06-04 14:50 UTC, CvRXX commented on platform/esp/hal_spi_esp.cpp
> +            .user = new (callBackArgsBuffer.take().value()) CallbackArg{
this breaks when buffer is full, should be waiting

2021-06-08 13:51 UTC, CvRXX commented on platform/esp/hal_spi_esp.cpp
> +auto transactionBuffer = RingBuffer<spi_transaction_t, 10>();
Then you would have to pass both of them to the callback so it can free it again. I think this is the better option.

2021-06-09 08:35 UTC, CvRXX commented on app/brewblox-esp/main/graphics.hpp
> +        getInstance().display.writePixels(area->x1, area->x2, area->y1, area->y2, reinterpret_cast<uint8_t*>(color_p), nPixels);
I think it should be a class. It's a bit of memory that has functions related to it. It shouldn't be a class because there can only exist one at all times so it could be global data. However, this raises issues with initialisation. What if it runs before the main spi is initialised. 

The core guidelines also have an example for these singletons for this exact reason: 
https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#i3-avoid-singletons

2021-06-09 08:40 UTC, CvRXX commented on app/brewblox-esp/main/graphics.hpp
> +            ESP_LOGE("Flush", "Writing zero pixels");
fixed in 8a8df357

2021-06-09 08:41 UTC, CvRXX commented on app/brewblox-esp/main/graphics.hpp
> +            ESP_LOGE("Flush", "Writing zero pixels");
fixed in 8a8df357

2021-06-09 08:41 UTC, CvRXX commented on app/brewblox-esp/main/graphics.hpp
> +    TFT035 display = TFT035([&]() {
fixed in 8a8df357

2021-06-09 08:41 UTC, CvRXX commented on lib/inc/hal/hal_spi.h
> +    hal_spi_err_t write(const std::vector<uint8_t>& values, bool dma = false, std::function<void(TransactionData&)> pre = nullptr, std::function<void(TransactionData&)> post = nullptr)
fixed in 8a8df357

2021-06-09 08:42 UTC, CvRXX commented on lib/inc/hal/hal_spi.h
> +        return platform_spi::write(settings, values.data(), values.size(), dma, pre, post, SpiDataType::VALUE);
fixed in 8a8df357

2021-06-09 08:42 UTC, CvRXX commented on lib/inc/hal/hal_spi.h
> +    template <size_t N, std::enable_if_t<(N > 4), int> = 0>
fixed in 8a8df357

2021-06-09 08:42 UTC, CvRXX commented on lib/inc/hal/hal_spi_types.h
> +struct Transaction {
fixed in 8a8df357

2021-06-09 08:42 UTC, CvRXX commented on lib/inc/hal/hal_spi_types.h
> +struct Transaction {
fixed in 8a8df357

2021-06-09 08:43 UTC, CvRXX commented on lib/test/ringBuffer_test.cpp
> +TEST_CASE("Elements can be taken from the ringbuffer", "[ringBuffer]")
Ringbuffer is not used anymore but the new `StaticAllocator` has a line coverage of 100%.
fixed in 8a8df357

2021-06-09 08:50 UTC, CvRXX commented on platform/esp/hal_spi_esp.cpp
> +        .tx_len = t->length,
fixed in 8a8df35

2021-06-09 08:50 UTC, CvRXX commented on platform/esp/hal_spi_esp.cpp
> +    t->length = transactionData.tx_len;
fixed in 8a8df35

2021-06-09 08:56 UTC, CvRXX commented on platform/esp/TFT035.cpp
> +TFT035::TFT035(std::function<void()> finishCallback)
I'm having some issues with this. It is probably best to talk about this in person.

2021-08-09 14:50 UTC, merged